---
# file: roles/vagrant/tasks/setup-RedHat.yml

- name: "RedHat: Install dependencies"
  become: true
  ansible.builtin.dnf:
    name: "{{ vagrant_dependencies }}"
    state: present
    update_cache: true

- name: "RedHat: Add Hashicorps's signing key"
  become: true
  ansible.builtin.rpm_key:
    key: "{{ hashicorp_public_key }}"
    state: "{{ hashicorp_public_key_state }}"

- name: "Amazon: Add Hashicorp's repository"
  become: true
  ansible.builtin.yum_repository:
    name: HashiCorp
    description: HashiCorp Stable - $basearch
    baseurl: https://rpm.releases.hashicorp.com/AmazonLinux/latest/$basearch/stable
    enabled: true
    gpgcheck: true
    mode: "0644"
  when:
    - ansible_facts.distribution == "Amazon"

- name: "Fedora: Add Hashicorp's repository"
  become: true
  ansible.builtin.yum_repository:
    name: HashiCorp
    description: HashiCorp Stable - $basearch
    baseurl: https://rpm.releases.hashicorp.com/fedora/$releasever/$basearch/stable
    enabled: true
    gpgcheck: true
    mode: "0644"
  when:
    - ansible_facts.distribution == "Fedora"

- name: "RedHat: Add Hashicorp's repository"
  become: true
  ansible.builtin.yum_repository:
    name: HashiCorp
    description: HashiCorp Stable - $basearch
    baseurl: https://rpm.releases.hashicorp.com/RHEL/$releasever/$basearch/stable
    enabled: true
    gpgcheck: true
    mode: "0644"
  when:
    - not ansible_facts.distribution == "Amazon"
    - not ansible_facts.distribution == "Fedora"

- name: "Installing vagrant packages"
  become: true
  ansible.builtin.package:
    name: "{{ vagrant_packages }}"
    state: "{{ vagrant_packages_state }}"
