---
# file: roles/vagrant/tasks/setup-Debian.yml

- name: "Debian: Install dependencies"
  become: true
  ansible.builtin.apt:
    name: "{{ vagrant_dependencies }}"
    state: present
    update_cache: true

- name: "Debian: Set release for apt repository"
  ansible.builtin.set_fact:
    debian_ubuntu_release: "{{ ansible_facts.distribution_release }}"
  when: ansible_facts.distribution != "Linux Mint"

- name: Get release for Linux Mint
  when: not ansible_check_mode and ansible_facts.distribution == "Linux Mint"
  block:
    - name: "Linux Mint: Get distribution release"
      ansible.builtin.command: grep -oP 'UBUNTU_CODENAME=\K.*' /etc/os-release
      register: distro
      changed_when: false
    - name: "Linux Mint: Set release for apt repository"
      ansible.builtin.set_fact:
        debian_ubuntu_release: "{{ distro.stdout }}"

- name: "Debian: Get dpkg architecture"
  ansible.builtin.command: dpkg --print-architecture
  register: dpkg_arch
  changed_when: false
  check_mode: false

- name: "Debian 11: Add HashiCorp repo"
  when: ansible_facts.distribution == "Ubuntu" or
    (ansible_facts.distribution == "Debian" and
    ansible_facts.distribution_major_version | int == 11)
  block:
    - name: "Debian: Add Hashicorp's signing key"
      become: true
      ansible.builtin.apt_key:
        url: "{{ hashicorp_public_key }}"
        state: "{{ hashicorp_public_key_state }}"

    - name: "Debian: Setup Hashicorp's apt repository"
      become: true
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ dpkg_arch.stdout }}] https://apt.releases.hashicorp.com {{ debian_ubuntu_release }} main"
        filename: hashicorp
        state: present
        mode: "0644"
        update_cache: false

- name: "Debian >= 12: Setup Hashicorp's apt repository"
  become: true
  ansible.builtin.deb822_repository:
    name: hashicorp
    types: deb
    uris: "https://apt.releases.hashicorp.com"
    architectures: "{{ dpkg_arch.stdout }}"
    suites: "{{ debian_ubuntu_release }}"
    components: main
    signed_by: "{{ hashicorp_public_key }}"
    state: present
    enabled: true
    install_python_debian: true
  when:
    - ansible_facts.distribution == "Debian"
    - ansible_facts.distribution_major_version | int >= 12

- name: "Installing vagrant packages"
  become: true
  ansible.builtin.apt:
    name: "{{ vagrant_packages }}"
    state: "{{ vagrant_packages_state }}"
    update_cache: true
