---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Gather installed package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Assert vagrant is installed
      ansible.builtin.assert:
        that:
          - "'vagrant' in ansible_facts.packages"
        fail_msg: "vagrant is not installed"
        success_msg: "vagrant is installed"
