---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Gather installed package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Assert vagrant is installed
      ansible.builtin.assert:
        that:
          - "'vagrant' in ansible_facts.packages"
        fail_msg: "vagrant is not installed"
        success_msg: "vagrant is installed"

    - name: "Get vagrant version"
      become: true
      become_user: ansible
      ansible.builtin.command: vagrant --version
      changed_when: false
      register: vagrant_version

    - name: "Show vagrant version"
      ansible.builtin.debug:
        msg: "{{ vagrant_version.stdout }}"
